# Generated by Django 5.2.4 on 2025-10-14 23:15

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_movie_genre_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="emb",
            field=models.BinaryField(default=movie.models.get_default_array),
        ),
    ]
